version: "3.8"
services:
  app:
    image: php:8.0-apache
    volumes:
      - "./app:/var/www/html/"
  proxy:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./proxy.conf:/etc/nginx/nginx.conf:ro"
